# Generated by Django 5.1.4 on 2025-01-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebalance',
            name='carried_forward',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='total_days',
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='used_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
