# Generated by Django 5.1.4 on 2025-01-20 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_leavebalance_remaining_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebalance',
            name='remaining_days',
        ),
    ]
